version: "3"

services:
  minecraft:
    container_name: minecraftserver
    image: ${IMAGE:-itzg/minecraft-server}
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: "1.20.1"
      FORGE_INSTALLER: "forge-1.20.1-47.2.20-installer.jar"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      JVM_XX_OPTS: -Xms8G -Xmx12G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
      MAX_MEMORY: 12G
      MAX_PLAYERS: 1
      MOTD: "Minecraft ATM 9 TTS"
      DIFFICULTY: normal
      SPAWN_PROTECTION: 0
      ENFORCE_WHITELIST: "true"
      WHITELIST: PLAYER
      OPS: PLAYER
    ports:
      - 25565:25565
    volumes:
      - ./server-data:/data
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    restart: unless-stopped
